language: node_js
node_js:
- "0.12"

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli
- cd /tmp
- /home/travis/build/appdevdesigns/nextsteps-server/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/nextsteps-server .
- cd nextsteps-server
- npm install mocha chai 
- npm install

script:
- npm test
 
